version: "3"

services:
  ruby:
    build:
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle

volumes:
  bundle: